"""Case compiler — compiles test_cases/analytical/vdf_grid.yml into
kernel/tests_cpp/vdf_cases.inc (a plain C initializer list).

The YAML is the single source. Both C++ executables consume the compiled
.inc; the external Python oracle reads the YAML directly, so an error here
surfaces as a three-way disagreement rather than a silent shared bug.

Run:  python test_cases/case_compiler.py [--check]
      --check: exit 1 if the committed .inc differs from fresh output.
"""
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
YML = os.path.join(HERE, "analytical", "vdf_grid.yml")
OUT = os.path.join(HERE, "..", "kernel", "tests_cpp", "vdf_cases.inc")

FIELDS = [  # (yaml key, C field, default)
    ("alpha", "alpha", 0.15), ("beta", "beta", 4.0),
    ("mbpr_A", "mbpr_A", 0.0),
    ("conic_a", "conic_a", 0.0), ("conic_b", "conic_b", 0.0),
    ("q_cp", "q_cp", 0.28125), ("q_cd", "q_cd", 1.0),
    ("q_n", "q_n", 1.24), ("q_s", "q_s", 4.0),
    ("green_ratio", "green_ratio", 0.45),
    ("cycle_length_s", "cycle_length_s", 90.0),
    ("added_delay_per_mile", "added_delay_per_mile", 0.0),
]


def compile_yaml():
    spec = yaml.safe_load(open(YML))
    lines = ["// GENERATED by test_cases/case_compiler.py from "
             "test_cases/analytical/vdf_grid.yml — do not edit.",
             "// Regenerate: python test_cases/case_compiler.py",
             "static const double CASE_GRID[] = {"
             + ", ".join(repr(float(x)) for x in spec["grid"]) + "};",
             "static const int CASE_NG = %d;" % len(spec["grid"]),
             "struct VdfCase { const char* id; int kernel_id;"]
    lines.append("  double " + ", ".join(c for _, c, _ in FIELDS) + "; };")
    lines.append("static const VdfCase CASES[] = {")
    for c in spec["cases"]:
        vals = ", ".join(repr(float(c.get(k, d))) for k, _, d in FIELDS)
        lines.append('  {"%s", %d, %s},' % (c["id"], int(c["kernel_id"]), vals))
    lines.append("};")
    lines.append("static const int N_CASES = %d;" % len(spec["cases"]))
    lines.append("static const double CASE_REL_TOL = %s;"
                 % repr(float(spec["tolerances"]["rel"])))
    return "\n".join(lines) + "\n"


def main():
    text = compile_yaml()
    if "--check" in sys.argv:
        old = open(OUT).read() if os.path.exists(OUT) else ""
        if old != text:
            print("vdf_cases.inc is STALE — rerun the case compiler")
            sys.exit(1)
        print("vdf_cases.inc up to date")
        return
    with open(OUT, "w", newline="\n") as f:
        f.write(text)
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
